// USJレストラン診断データ
// ソース: ~/USJ-Knowledge/USJ/レストラン/
// ※ 食べ歩きフードは本診断の対象外です

const RESTAURANTS = [
  {
    id: "mels",
    name: "メルズ・ドライブイン",
    area: "ハリウッド",
    areaId: "hollywood",
    genre: "アメリカン（ハンバーガー・チキン）",
    budget: "1,200〜2,000円",
    budgetMin: 1200,
    seatType: "テーブル席・テラス席",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11:30前 or 14:00以降",
    crowdLevel: "普通",
    character: null,
    kidsFriendly: "キッズメニューあり、ハイチェア完備、テラスで開放的に食事可能",
    mainMenu: ["トリプルチーズバーガーセット", "BBQベーコンチーズバーガーセット", "フライドチキン", "アップルパイ"],
    collab: null,
    collabMenu: null,
    features: "1950年代アメリカンダイナーを再現。席数が多く回転も早い。",
    foodCategories: ["ハンバーガー", "デザート・スイーツ"]
  },
  {
    id: "happiness",
    name: "ハピネス・カフェ",
    area: "サンフランシスコ",
    areaId: "sanfrancisco",
    genre: "ハンバーガー・カレーなど",
    budget: "1,200〜2,000円",
    budgetMin: 1200,
    seatType: "テーブル席",
    capacity: "非常に多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11:30前 or 14:00以降（席を確保してから並ぶと効率的）",
    crowdLevel: "普通",
    character: "ミニオン",
    kidsFriendly: "キッズメニューあり、ハイチェア完備、広くベビーカー対応",
    mainMenu: ["ボブのワッフルチキンプレート", "スチュアートのベーコンチーズバーガープレート", "デイブのキーマカレープレート", "ミニオン・キッズセット"],
    collab: null,
    collabMenu: null,
    features: "パーク内最大級の座席数を誇るフードコート形式。万人向けメニュー豊富。",
    foodCategories: ["ハンバーガー", "カレー"]
  },
  {
    id: "discovery",
    name: "ディスカバリー・レストラン",
    area: "ジュラシック・パーク",
    areaId: "jurassic",
    genre: "洋食（チキン・ハンバーガーなど）",
    budget: "1,200〜2,000円",
    budgetMin: 1200,
    seatType: "テーブル席（テラス席もあり）",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11:30前 or 14:00以降",
    crowdLevel: "穴場",
    character: "恐竜（ジュラシック・パーク）",
    kidsFriendly: "キッズメニューあり、ハイチェア完備、恐竜好きの子向け",
    mainMenu: ["ハリウッド・ドリーム・チーズバーガーセット", "ローストビーフ・サンドセット", "スパイシー・ジャンバラヤ"],
    collab: null,
    collabMenu: null,
    features: "メインエリアから少し離れているため比較的空いている穴場。恐竜の世界観。",
    foodCategories: ["ハンバーガー"]
  },
  {
    id: "louis",
    name: "ルイズN.Y.ピザパーラー",
    area: "ニューヨーク",
    areaId: "newyork",
    genre: "ピザ",
    budget: "800〜1,500円",
    budgetMin: 800,
    seatType: "テーブル席",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11:30前 or 14:00以降",
    crowdLevel: "穴場",
    character: null,
    kidsFriendly: "ピザは子ども向け、手軽でシェアしやすい",
    mainMenu: ["マルゲリータピッツァ", "ペパロニピッツァ", "クアトロチーズ＆ハチミツピッツァ"],
    collab: null,
    collabMenu: null,
    features: "ニューヨークスタイルの大きなピザ。提供が早く回転も良い穴場。コスパ◎",
    foodCategories: ["ピザ・パスタ"]
  },
  {
    id: "kinopio",
    name: "キノピオ・カフェ",
    area: "ニンテンドーワールド",
    areaId: "nintendo",
    genre: "洋食（パスタ・ハンバーガーなど）",
    budget: "1,500〜2,500円",
    budgetMin: 1500,
    seatType: "テーブル席",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11時前 or 14時以降",
    crowdLevel: "混雑",
    character: "マリオ",
    kidsFriendly: "キッズメニューあり、ハイチェア完備、ベビーケアルームあり、キャラクターフードで子ども大喜び",
    mainMenu: ["マリオ・バーガー", "ルイージ・バーガー", "ヨッシー・スパゲティ", "大魔王クッパ・ハンバーグステーキ"],
    collab: null,
    collabMenu: null,
    features: "マリオの世界観を再現。キノコやスター型のキャラクターフードが楽しめる。",
    foodCategories: ["ハンバーガー", "ピザ・パスタ"]
  },
  {
    id: "parkside",
    name: "パークサイド・グリル",
    area: "ハリウッド",
    areaId: "hollywood",
    genre: "ステーキ・グリル",
    budget: "3,000〜5,000円",
    budgetMin: 3000,
    seatType: "テーブル席（着席サービス）",
    capacity: "中程度",
    peakTime: "11:30〜13:30",
    recommendedTime: "価格帯が高いため比較的空いている",
    crowdLevel: "穴場",
    character: null,
    kidsFriendly: "キッズメニューあり。落ち着いた雰囲気で特別な日向け",
    mainMenu: ["エイジングステーキ", "サーモン", "ラムチョップ", "阿波尾鶏"],
    collab: null,
    collabMenu: null,
    features: "パーク内の高級レストラン。落ち着いた雰囲気でゆっくり食事できる。",
    foodCategories: ["ステーキ・肉料理"]
  },
  {
    id: "saido",
    name: "SAIDO（彩道）",
    area: "ニューヨーク",
    areaId: "newyork",
    genre: "和食（うどん・天ぷら・丼など）",
    budget: "1,500〜2,500円",
    budgetMin: 1500,
    seatType: "テーブル席",
    capacity: "中程度",
    peakTime: "11:30〜13:30",
    recommendedTime: "11時頃 or 14時以降",
    crowdLevel: "普通",
    character: null,
    kidsFriendly: "キッズメニューあり、ハイチェア完備、うどんは子どもが食べやすい",
    mainMenu: ["うどん各種", "天ぷらセット", "丼もの"],
    collab: null,
    collabMenu: null,
    features: "パーク内唯一の本格和食レストラン。洋食に飽きた時に重宝。",
    foodCategories: ["和食"]
  },
  {
    id: "dragons",
    name: "ドラゴンズ・パール",
    area: "サンフランシスコ",
    areaId: "sanfrancisco",
    genre: "中華",
    budget: "1,200〜2,000円",
    budgetMin: 1200,
    seatType: "テーブル席",
    capacity: "中程度",
    peakTime: "11:30〜13:30",
    recommendedTime: "11:30前 or 14:00以降",
    crowdLevel: "穴場",
    character: null,
    kidsFriendly: "キッズメニューあり、ハイチェア完備",
    mainMenu: ["チャーハン各種", "ジャージャー麺", "麻婆豆腐", "鳥の唐揚げ香味たれ"],
    collab: null,
    collabMenu: null,
    features: "中華料理レストラン。中華を選ぶ人が少ないため比較的空いている穴場。",
    foodCategories: ["中華"]
  },
  {
    id: "broomsticks",
    name: "三本の箒",
    area: "ハリー・ポッター",
    areaId: "harrypotter",
    genre: "イギリス料理（ロースト・フィッシュ&チップスなど）",
    budget: "1,500〜3,000円",
    budgetMin: 1500,
    seatType: "テーブル席",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11時前 or 14時以降",
    crowdLevel: "混雑",
    character: "ハリー・ポッター",
    kidsFriendly: "キッズメニューあり、ハイチェア完備、バタービール人気（甘い）",
    mainMenu: ["フィッシュ＆チップス", "ローストビーフ", "ロティサリー・スモークチキン＆ポークリブ", "バタービール™"],
    collab: null,
    collabMenu: null,
    features: "ホグズミード村の食堂を再現。バタービールが飲める唯一のレストラン。",
    foodCategories: ["イギリス料理"]
  },
  {
    id: "amity",
    name: "アミティ・ランディング・レストラン",
    area: "アミティ・ビレッジ",
    areaId: "amity",
    genre: "シーフード・洋食",
    budget: "1,200〜2,000円",
    budgetMin: 1200,
    seatType: "テーブル席",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11:30前 or 14:00以降",
    crowdLevel: "穴場",
    character: "ジョーズ",
    kidsFriendly: "キッズメニューあり、ハイチェア完備",
    mainMenu: ["スパイシーシュリンプ・ブリトーセット", "チキン＆アボカド・ブリトーセット", "バーベキューポーク・ブリトーセット"],
    collab: null,
    collabMenu: null,
    features: "ジョーズの隣にある港町の雰囲気。比較的空いている穴場。",
    foodCategories: ["軽食"]
  },
  {
    id: "snoopy",
    name: "スヌーピー・バックロット・カフェ",
    area: "ワンダーランド",
    areaId: "wonderland",
    genre: "洋食（ハンバーガー・パスタ・カレーなど）",
    budget: "1,200〜2,000円",
    budgetMin: 1200,
    seatType: "テーブル席",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11時前 or 14時以降",
    crowdLevel: "混雑",
    character: "スヌーピー",
    kidsFriendly: "キッズメニュー充実、ハイチェア完備、離乳食持ち込みOK、ベビーケアルームあり",
    mainMenu: ["クリーミースープパスタセット", "テリヤキビーフバーガーセット", "エビカツバーガーセット", "スヌーピー・キッズセット"],
    collab: null,
    collabMenu: null,
    features: "子連れに一番人気。ワンダーランド中心部でアトラクション合間の食事に最適。",
    foodCategories: ["ハンバーガー", "ピザ・パスタ", "カレー"]
  },
  {
    id: "lostworld",
    name: "ロストワールド・レストラン",
    area: "ロストワールド",
    areaId: "lostworld",
    genre: "洋食・創作料理",
    budget: "1,500〜3,000円",
    budgetMin: 1500,
    seatType: "テーブル席",
    capacity: "中程度",
    peakTime: "11:30〜13:30",
    recommendedTime: "11:30前 or 14:00以降",
    crowdLevel: "普通",
    character: "モンスターハンター",
    kidsFriendly: "キッズメニューあり",
    mainMenu: ["焚き火料理 ポーク", "焚き火料理 チキン", "オトモアイルーのチョコレートプリン"],
    collab: "モンスターハンター ワイルズ",
    collabMenu: ["限定コースターセット", "オトモアイルーのチョコレートプリンマグカップ付き"],
    features: "モンスターハンターの世界観を再現した創作料理。ゲームファンに人気。",
    foodCategories: ["ステーキ・肉料理", "デザート・スイーツ"]
  },
  {
    id: "studiostars",
    name: "スタジオ・スターズ・レストラン",
    area: "ハリウッド",
    areaId: "hollywood",
    genre: "洋食（プレート料理・カレー・グラタンなど）",
    budget: "2,200〜2,600円",
    budgetMin: 2200,
    seatType: "テーブル席",
    capacity: "多い",
    peakTime: "11:30〜13:30",
    recommendedTime: "11時前 or 14時以降",
    crowdLevel: "普通",
    character: null,
    collab: "25周年スペシャル",
    collabMenu: ["25周年スペシャルプレート", "25周年アニバーサリー・ドリンクカップ"],
    kidsFriendly: "キッズメニューあり（¥1,000）、ハイチェア完備、デザート充実",
    mainMenu: ["BBQポークリブ&フライドチキン・プレート", "BLTバーガー・プレート", "チキンレッグカレー・プレート", "クラムチャウダーグラタン・プレート"],
    features: "プレート料理やデザートが充実。25周年スペシャルメニュー展開中。",
    foodCategories: ["ハンバーガー", "カレー", "デザート・スイーツ"]
  },
  {
    id: "beverly",
    name: "ビバリーヒルズ・ブランジェリー",
    area: "ハリウッド",
    areaId: "hollywood",
    genre: "ベーカリー・カフェ",
    budget: "500〜2,100円",
    budgetMin: 500,
    seatType: "テーブル席",
    capacity: "中程度",
    peakTime: "11:30〜13:30",
    recommendedTime: "比較的空いている（軽食メインのため）",
    crowdLevel: "穴場",
    character: null,
    collab: "呪術廻戦",
    collabMenu: ["呪術高専1年のサンドウィッチセット", "夏油傑のムース", "五条悟のムース", "呪術高専のグレープフルーツ・レモネード"],
    kidsFriendly: "パンは小さい子にも食べさせやすい、テイクアウト可",
    mainMenu: ["サンドウィッチセット", "ホットサンド", "各種パン", "スイーツ各種"],
    features: "パン・サンドイッチ・スイーツが揃うベーカリーカフェ。軽食やおやつ休憩に便利な穴場。",
    foodCategories: ["軽食", "デザート・スイーツ"]
  }
];

// フード分類の定義
const FOOD_CATEGORIES = [
  { id: "burger", label: "ハンバーガー", icon: "🍔" },
  { id: "pizza", label: "ピザ・パスタ", icon: "🍕" },
  { id: "steak", label: "ステーキ・肉料理", icon: "🥩" },
  { id: "japanese", label: "和食（うどん・天ぷら）", icon: "🍜" },
  { id: "chinese", label: "中華", icon: "🥟" },
  { id: "british", label: "イギリス料理", icon: "🐟" },
  { id: "curry", label: "カレー", icon: "🍛" },
  { id: "dessert", label: "デザート・スイーツ", icon: "🍰" },
  { id: "light", label: "軽め（パン・サンド）", icon: "🥪" },
  { id: "any", label: "なんでもOK", icon: "✨" }
];

// フード分類のマッピング
const FOOD_CATEGORY_MAP = {
  "ハンバーガー": "burger",
  "ピザ・パスタ": "pizza",
  "ステーキ・肉料理": "steak",
  "和食": "japanese",
  "中華": "chinese",
  "イギリス料理": "british",
  "カレー": "curry",
  "デザート・スイーツ": "dessert",
  "軽食": "light"
};

// キャラクター分類の定義
const CHARACTERS = [
  { id: "mario", label: "マリオ", icon: "🍄" },
  { id: "harrypotter", label: "ハリー・ポッター", icon: "⚡" },
  { id: "minion", label: "ミニオン", icon: "🍌" },
  { id: "snoopy", label: "スヌーピー", icon: "🐶" },
  { id: "dinosaur", label: "恐竜（ジュラシック）", icon: "🦕" },
  { id: "monsterhunter", label: "モンスターハンター", icon: "⚔️" },
  { id: "jaws", label: "ジョーズ", icon: "🦈" },
  { id: "none", label: "特にない", icon: "🍽️" }
];

// キャラクターマッピング
const CHARACTER_MAP = {
  "マリオ": "mario",
  "ハリー・ポッター": "harrypotter",
  "ミニオン": "minion",
  "スヌーピー": "snoopy",
  "恐竜（ジュラシック・パーク）": "dinosaur",
  "モンスターハンター": "monsterhunter",
  "ジョーズ": "jaws"
};

// エリア分類の定義
const AREAS = [
  { id: "hollywood", label: "ハリウッド付近", icon: "🎬" },
  { id: "newyork_sf", label: "ニューヨーク〜サンフランシスコ", icon: "🏙️" },
  { id: "nintendo", label: "ニンテンドーワールド", icon: "🎮" },
  { id: "harrypotter", label: "ハリー・ポッターエリア", icon: "🧙" },
  { id: "wonderland_jurassic", label: "ワンダーランド〜ジュラシック", icon: "🎠" },
  { id: "anywhere", label: "決まってない", icon: "🗺️" }
];

// エリアのグループマッピング
const AREA_GROUP_MAP = {
  "hollywood": ["hollywood"],
  "newyork_sf": ["newyork", "sanfrancisco"],
  "nintendo": ["nintendo"],
  "harrypotter": ["harrypotter"],
  "wonderland_jurassic": ["wonderland", "jurassic", "lostworld", "amity"],
  "anywhere": []
};

// 時間帯の定義
const TIME_SLOTS = [
  { id: "morning", label: "朝〜午前中（〜11:00）", icon: "🌅" },
  { id: "lunch", label: "ランチ（11:00〜14:00）", icon: "☀️" },
  { id: "afternoon", label: "遅めランチ / おやつ（14:00〜16:00）", icon: "🍵" },
  { id: "dinner", label: "ディナー（16:00〜閉園）", icon: "🌙" }
];

// 重視ポイントの定義
const PRIORITIES = [
  { id: "avoid_crowd", label: "混雑を避けたい", icon: "🚶" },
  { id: "kids", label: "子どもが喜ぶ", icon: "👶" },
  { id: "atmosphere", label: "映え・世界観重視", icon: "📸" },
  { id: "cospa", label: "コスパ重視", icon: "💰" },
  { id: "relax", label: "ゆっくり座りたい", icon: "🪑" }
];
